name: clear space
favicon: null
layout_spectrum: 0.1803141611162573
typography_spectrum: 0.8697349987924099
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.45221086614765227
  lightness: 0.46619703713804483
  saturation: 0.7524360539391637
  rhythmicContrast: 0.21297924686223269
purpose: []
